# gui apps

## software development

### browser
cask "brave-browser"
cask "google-chrome"

### ide
cask "visual-studio-code"
cask "antigravity"

### ai/ml tools
cask "lm-studio"

## utilities

### microsoft office
cask "microsoft-word"
cask "microsoft-excel"
cask "microsoft-powerpoint"

### others
cask "cloudflare-warp"
cask "rectangle"
cask "keka"
cask "kap"
cask "iina"
cask "motrix"
cask "utm"
