# gui apps

## software development

### browser
cask "helium-browser"
cask "google-chrome"

### ide
cask "visual-studio-code"

### container & orchestration
cask "davit"

### ai/ml tools
cask "claude"
cask "claude-code"
cask "codex"
cask "codex-app"
cask "lm-studio"

### research & paper writing
cask "quarto"
cask "zotero"

## utilities

### office
cask "microsoft-word"
cask "microsoft-excel"
cask "microsoft-powerpoint"

### knowledge base
cask "obsidian"
cask "tolaria"

### virtualization & remote desktop
cask "utm"
cask "windows-app"

### system monitoring
cask "coconutbattery"

### others
cask "cloudflare-warp"
cask "rectangle"
cask "keka"
cask "iina"
cask "motrix"
