# homebrew
if [[ "$(uname)" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# gh
eval "$(gh copilot alias -- zsh)"

# fnm
eval "$(fnm env --use-on-cd)"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

# spaceship-prompt
source "$(brew --prefix)/opt/spaceship/spaceship.zsh"

# oh-my-zsh
plugins=(git gh fnm npm pyenv poetry poetry-env podman kind kubectl terraform aws direnv)
source "$HOME/.oh-my-zsh/oh-my-zsh.sh"

# zsh aliases
source "$HOME/.zsh_aliases"

# zsh-autosuggestions
source /home/linuxbrew/.linuxbrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# zsh-completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

# zsh-syntax-highlighting
source /home/linuxbrew/.linuxbrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
