# homebrew
if [[ "$(uname)" == "Darwin" ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# fnm
eval "$(fnm env --use-on-cd)"

# spaceship-prompt
source $(brew --prefix)/opt/spaceship/spaceship.zsh

# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
plugins=(git gh fnm npm podman kind kubectl terraform aws direnv thefuck)
source $ZSH/oh-my-zsh.sh

# aliases

## ssh
ssha() { eval $(ssh-agent -s); ssh-add "$@"; }
alias ssht="ssh -T"
alias sshtgh="ssh -T git@github.com"
alias sshtgl="ssh -T git@gitlab.com"

## docker
alias docker=podman

## other
alias clean="rm ~/.zsh_history"
alias myip="curl https://ipecho.net/plain; echo"
