# cli
brew yarn
brew minikube
brew mkcert
brew thefuck

# browser
cask station
cask brave-browser

# development
cask docker
cask visual-studio-code
cask sequel-pro
cask robo-3t
cask postman

# utilities
cask alfred
cask spectacle
cask the-unarchiver
cask vlc
cask webtorrent
