# cli apps

## software development
brew "gpg"
brew "nvm"
brew "yarn"
brew "docker-compose"
brew "kubectl"
brew "minikube"
brew "kustomize"
# brew "skaffold"
# brew "helm"
brew "mkcert"
brew "httpie"

## utilities
brew "thefuck"


# gui apps

## software development
cask "brave-browser"
cask "docker"
cask "lens"
cask "visual-studio-code"
cask "sequel-pro"
cask "robo-3t"
cask "Casks/medis.rb"
cask "postman"

## utilities
cask "alfred"
cask "spectacle"
cask "the-unarchiver"
cask "vlc"
cask "motrix"
