# cli tools
brew nvm
brew yarn
brew docker
brew docker-compose
brew minikube
brew mkcert
brew thefuck
brew httpie

# macos apps

# browser
cask station
cask brave-browser

# development
cask visual-studio-code
cask sequel-pro
cask robo-3t
cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/7ceeedb95e3351006ab1376772eaac8d3745aabb/Casks/medis.rb
cask postman

# utilities
cask alfred
cask spectacle
cask the-unarchiver
cask vlc
cask motrix
